motoristas/urls.py
# motoristas/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('cadastrar/', views.cadastrar_motorista, name='cadastrar_motorista'),
    path('', views.listar_motoristas, name='listar_motoristas'),
    path('login/', views.login_view, name='login_motorista'),
    path('home/', views.home_motorista, name='home_motorista'),  # Adicione esta linha
    path('logout/', views.logout_view, name='logout_motorista'),  # Adicione esta linha
    path('gerar_senha/<str:cpf>/', views.gerar_senha_temporaria, name='gerar_senha_temporaria'),  # Nova URL
    path('deletar/<str:cpf>/', views.deletar_motorista, name='deletar_motorista'),  # Nova URL
]

ps_voucher/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('motoristas/', include('motoristas.urls')),
    path('vouchers/', include('vouchers.urls')),
    path('postos/', include('postos.urls')),  # Adicione esta linha
    path('rotas/', include('rotas.urls')),  # Adicione esta linha
    path('usuarios/', include('usuarios.urls')),
    path('analise_posto/', include('analise_posto.urls')),  # Adiciona o novo app de análise
    path('accounts/', include('django.contrib.auth.urls')),  # Adiciona URLs de autenticação padrão do Django
    path('', TemplateView.as_view(template_name='home.html'), name='home'),  # Adiciona a URL da página inicial
]

if settings.DEBUG or settings.SERVE_MEDIA_IN_PROD:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

rotas/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('cadastrar/', views.cadastrar_rota, name='cadastrar_rota'),
    path('', views.listar_rotas, name='listar_rotas'),
    path('editar/<int:rota_id>/', views.editar_rota, name='editar_rota'),
    path('deletar/<int:rota_id>/', views.deletar_rota, name='deletar_rota'),
]

motoristas/models.py
from django.db import models

class Motorista(models.Model):
    nome = models.CharField(max_length=100)
    cpf = models.CharField(max_length=11, unique=True)
    placa_veiculo = models.CharField(max_length=7)

    def __str__(self):
        return self.nome

motoristas/forms.py
# motoristas/forms.py
from django import forms
from django.contrib.auth.models import User, Group
from .models import Motorista
import random
import string

class LoginForm(forms.Form):
    cpf = forms.CharField(max_length=11)
    senha = forms.CharField(widget=forms.PasswordInput)

class MotoristaForm(forms.ModelForm):
    class Meta:
        model = Motorista
        fields = ['nome', 'cpf', 'placa_veiculo']
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control'}),
            'cpf': forms.TextInput(attrs={'class': 'form-control'}),
            'placa_veiculo': forms.TextInput(attrs={'class': 'form-control'}),
        }

motoristas/views.py
import random
import string
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from usuarios.decorators import group_required
from django.contrib.auth.models import User, Group
from django.http import JsonResponse
from django.contrib.auth import authenticate, login, logout
from vouchers.models import Voucher
from .models import Motorista
from .forms import MotoristaForm, LoginForm
from django.contrib.auth.decorators import login_required

# Variável global para armazenar senhas temporárias
motorista_senhas = {}

@login_required
@group_required('Administrador', 'RMO')
def cadastrar_motorista(request):
    if request.method == 'POST':
        form = MotoristaForm(request.POST)
        if form.is_valid():
            motorista = form.save()
            grupo_padrao, created = Group.objects.get_or_create(name='Motorista')
            senha = ''.join(random.choices(string.ascii_letters + string.digits, k=8))
            user = User.objects.create_user(username=motorista.cpf, password=senha)
            motorista_senhas[motorista.cpf] = senha  # Armazenar a senha temporariamente
            print(f'Senha gerada para {motorista.nome}: {senha}')
            return redirect('listar_motoristas')
    else:
        form = MotoristaForm()
    return render(request, 'motoristas/cadastrar_motorista.html', {'form': form})

@login_required
@group_required('Administrador', 'RMO')
def listar_motoristas(request):
    motoristas = Motorista.objects.all()
    motoristas_com_senhas = [(motorista, motorista_senhas.get(motorista.cpf, '')) for motorista in motoristas]
    return render(request, 'motoristas/listar_motoristas.html', {'motoristas_com_senhas': motoristas_com_senhas})

def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cpf = form.cleaned_data['cpf']
            senha = form.cleaned_data['senha']
            user = authenticate(request, username=cpf, password=senha)
            if user is not None:
                login(request, user)
                return redirect('home_motorista')
            else:
                form.add_error(None, 'CPF ou senha inválidos')
    else:
        form = LoginForm()
    return render(request, 'motoristas/login.html', {'form': form})

@login_required
def home_motorista(request):
    motorista = Motorista.objects.get(cpf=request.user.username)
    vouchers = Voucher.objects.filter(motorista=motorista).exclude(status__in=['Usado', 'Expirado'])
    return render(request, 'motoristas/home_motorista.html', {'motorista': motorista, 'vouchers': vouchers})

def logout_view(request):
    logout(request)
    return redirect('home')

@login_required
@group_required('Administrador', 'RMO')
def gerar_senha_temporaria(request, cpf):
    senha = ''.join(random.choices(string.ascii_letters + string.digits, k=8))
    motorista = Motorista.objects.get(cpf=cpf)
    user = User.objects.get(username=cpf)
    user.set_password(senha)
    user.save()
    motorista_senhas[motorista.cpf] = senha
    return JsonResponse({'senha': senha})

@login_required
@group_required('Administrador')
def deletar_motorista(request, cpf):
    motorista = get_object_or_404(Motorista, cpf=cpf)
    user = User.objects.get(username=cpf)
    user.delete()
    motorista.delete()
    return redirect('listar_motoristas')

motoristas/templates/motoristas/cadastrar_motorista.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Cadastrar Motorista{% endblock %}

{% block content %}
<style> 
    body {
    font-family: 'Roboto', sans-serif;
    background-color: #f8f9fa;
    margin: 0;
    padding: 0;
}

.card {
    transition: transform 0.3s ease, box-shadow 0.3s ease;
}

.card:hover {
    transform: translateY(-10px);
    box-shadow: 0 10px 20px rgba(0, 0, 0, 0.2);
}

.animated {
    animation-duration: 1s;
    animation-fill-mode: both;
}

@keyframes fadeIn {
    from {
        opacity: 0;
    }
    to {
        opacity: 1;
    }
}

.fadeIn {
    animation-name: fadeIn;
}

</style>
<div class="d-flex flex-column align-items-center justify-content-center mt-5">
    <div class="card shadow-lg p-4 animated fadeIn" style="max-width: 100%; width: 100%; max-width: 600px; border-radius: 15px;">
        <div class="card-body">
            <h3 class="card-title text-center mb-4">Cadastrar Motorista</h3>
            <form method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="id_nome" class="form-label">Nome</label>
                    {{ form.nome }}
                </div>
                <div class="mb-3">
                    <label for="id_cpf" class="form-label">CPF</label>
                    {{ form.cpf }}
                </div>
                <div class="mb-3">
                    <label for="id_placa_veiculo" class="form-label">Placa do Veículo</label>
                    {{ form.placa_veiculo }}
                </div>
                <div class="d-grid">
                    <button type="submit" class="btn btn-primary btn-block">Cadastrar</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}

motoristas/templates/motoristas/home_motorista.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Home Motorista{% endblock %}

{% block content %}
<style>
.container {
    font-family: 'Roboto', sans-serif;
}

.card {
    background-color: #fff;
    border-radius: 15px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    transition: transform 0.3s ease, box-shadow 0.3s ease;
}

.card:hover {
    transform: translateY(-10px);
    box-shadow: 0 10px 20px rgba(0, 0, 0, 0.2);
}

.carousel {
    margin-top: 20px;
}

.carousel-control-prev-icon, 
.carousel-control-next-icon {
    background-color: #007bff;
    border-radius: 50%;
    padding: 10px;
}

.animated {
    animation-duration: 1s;
    animation-fill-mode: both;
}

@keyframes fadeIn {
    from {
        opacity: 0;
    }
    to {
        opacity: 1;
    }
}

.fadeIn {
    animation-name: fadeIn;
}

@media (max-width: 768px) {
    .card {
        width: 90%;
        margin: 0 auto;
    }
}
</style>

<div class="container mt-5">
    <div class="text-center mb-4 animated fadeIn">
        <h2>Bem-vindo, {{ motorista.nome }}</h2>
    </div>
    {% if vouchers %}
        <h3 class="mb-4 text-center animated fadeIn">Seus Vouchers:</h3>
        <div id="vouchersCarousel" class="carousel slide" data-bs-ride="carousel">
            <div class="carousel-inner">
                {% for voucher in vouchers %}
                <div class="carousel-item {% if forloop.first %}active{% endif %}">
                    <div class="d-flex justify-content-center">
                        <div class="card shadow-sm animated fadeIn" style="width: 18rem;">
                            <div class="card-body text-center">
                                <h5 class="card-title">Código: {{ voucher.codigo }}</h5>
                                <p class="card-text">
                                    <img src="{{ voucher.qr_code.url }}" alt="QR Code" class="img-fluid mb-3">
                                </p>
                                <p class="card-text">Valor: R$ {{ voucher.valor_restante }}</p>
                                <p class="card-text">Status: {{ voucher.status }}</p>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#vouchersCarousel" data-bs-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#vouchersCarousel" data-bs-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="visually-hidden">Next</span>
            </button>
        </div>
    {% else %}
        <p class="text-center animated fadeIn">Você não possui vouchers disponíveis no momento.</p>
    {% endif %}
</div>
{% endblock %}

motoristas/templates/motoristas/listar_motoristas.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Lista de Motoristas{% endblock %}

{% block content %}
<style>body {
    font-family: 'Roboto', sans-serif;
    background-color: #f8f9fa;
    margin: 0;
    padding: 0;
}

.card {
    transition: transform 0.3s ease, box-shadow 0.3s ease;
}

.card:hover {
    transform: translateY(-10px);
    box-shadow: 0 10px 20px rgba(0, 0, 0, 0.2);
}

.table-responsive {
    overflow-x: auto;
}

.animated {
    animation-duration: 1s;
    animation-fill-mode: both;
}

@keyframes fadeIn {
    from {
        opacity: 0;
    }
    to {
        opacity: 1;
    }
}

.fadeIn {
    animation-name: fadeIn;
}
</style>
<div class="d-flex flex-column align-items-center justify-content-center mt-5">
    <div class="card shadow-lg p-4 animated fadeIn" style="width: 100%; max-width: 1000px; border-radius: 15px;">
        <div class="card-body">
            <h3 class="card-title text-center mb-4">Lista de Motoristas</h3>
            <div class="table-responsive">
                <table class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Nome</th>
                            <th>CPF</th>
                            <th>Placa do Veículo</th>
                            <th>Senha (temporário)</th>
                            <th>Ações</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for motorista, senha in motoristas_com_senhas %}
                        <tr>
                            <td>{{ motorista.nome }}</td>
                            <td>{{ motorista.cpf }}</td>
                            <td>{{ motorista.placa_veiculo }}</td>
                            <td id="senha-{{ motorista.cpf }}">{{ senha }}</td> <!-- Senha temporária para testes -->
                            <td>
                                <button class="btn btn-secondary" onclick="gerarNovaSenha('{{ motorista.cpf }}')">Gerar Nova Senha</button>
                                <a href="{% url 'deletar_motorista' motorista.cpf %}" class="btn btn-danger">Excluir</a>
                            </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<script>
function gerarNovaSenha(cpf) {
    fetch(`/motoristas/gerar_senha/${cpf}/`)
    .then(response => response.json())
    .then(data => {
        if (data.error) {
            alert('Erro: ' + data.error);
        } else {
            document.getElementById(`senha-${cpf}`).textContent = data.senha;
        }
    })
    .catch(error => {
        console.error('Erro:', error);
    });
}
</script>
{% endblock %}

motoristas/templates/motoristas/login.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Login Motorista{% endblock %}

{% block content %}
<style>
.card {
    background-color: #fff;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    border-radius: 10px;
    transition: transform 0.3s ease, box-shadow 0.3s ease;
    margin: 10rem;
}

.card:hover {
    transform: translateY(-5px);
    box-shadow: 0 6px 12px rgba(0, 0, 0, 0.2);
}

.input-group-text {
    background-color: #E9ECEF;
    border-right: 0;
}

.input-group .form-control {
    border-left: 0;
}

.btn-success {
    background-color: #FFBD15;
    border-color: #FFBD15;
}

.btn-success:hover {
    background-color: #e2a918;
    border-color: #e2a918;
}

h3 {
    color: #E2A918;
    font-size: 1.5rem;
}

@media (max-width: 768px) {
    .card {
        width: 90%;
    }
}
</style>

<div class="d-flex flex-column align-items-center justify-content-center">
    <div class="card shadow-lg p-4 animated fadeIn" style="max-width: 100%; width: 100%; max-width: 350px;">
        <div class="card-body">
            <div class="text-center mb-4">
                <img src="{% static 'images/logo.png' %}" alt="Logo" class="mb-3" style="width: 120px;">
                <h3>Login Motorista</h3>
            </div>
            <form method="post">
                {% csrf_token %}
                <div class="mb-3 input-group">
                    <span class="input-group-text"><i class="fas fa-user"></i></span>
                    <input type="text" name="{{ form.cpf.name }}" class="form-control" placeholder="Seu usuário" required id="id_cpf">
                </div>
                <div class="mb-3 input-group">
                    <span class="input-group-text"><i class="fas fa-lock"></i></span>
                    <input type="password" name="{{ form.senha.name }}" class="form-control" placeholder="Sua senha" required id="id_senha">
                </div>
                <div class="d-grid mb-2">
                    <button type="submit" class="btn btn-success btn-block">ENTRAR</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock %}